# Generated by Django 5.2.6 on 2025-09-09 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "branding",
                    models.CharField(
                        choices=[
                            ("RPM", "RPM"),
                            ("BB", "Body Bike"),
                            ("OTHER", "Other"),
                        ],
                        default="RPM",
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("cover_artist", models.CharField(blank=True, max_length=255)),
                ("duration", models.DurationField()),
                (
                    "workout",
                    models.CharField(
                        choices=[
                            ("Walk in", "Walk in"),
                            ("Warmup", "Warmup"),
                            ("Mountain climb", "Mountain climb"),
                            ("Speed work", "Speed work"),
                            ("Ride home", "Ride home (cool down/stretch)"),
                            ("", ""),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="tracks.release",
                    ),
                ),
            ],
        ),
    ]
