# Generated by Django 5.2.6 on 2025-09-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="number",
            field=models.CharField(
                help_text="Track number within the release, can be non-numeric for bonus tracks",
                max_length=32,
            ),
        ),
    ]
