# Generated by Django 5.2.6 on 2025-09-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_alter_track_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="release",
            constraint=models.UniqueConstraint(
                fields=("number", "branding"), name="release_number_branding"
            ),
        ),
    ]
