# Generated by Django 5.2.6 on 2025-09-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0003_release_release_number_branding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="workout",
            field=models.CharField(
                choices=[
                    ("Walk in", "Walk in"),
                    ("Warmup", "Warmup"),
                    ("Pace", "Pace"),
                    ("Hills", "Hills"),
                    ("Mixed terrain", "Mixed terrain"),
                    ("Intervals", "Intervals"),
                    ("Speed work", "Speed work"),
                    ("Free spin", "Free spin"),
                    ("Mountain climb", "Mountain climb"),
                    ("Ride home", "Ride home (cool down)"),
                    ("Unknown", "Unknown"),
                    ("", "-"),
                ],
                default="Unknown",
                max_length=32,
            ),
        ),
    ]
