# Generated by Django 5.2.6 on 2025-09-10 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0004_alter_track_workout"),
    ]

    operations = [
        migrations.RenameField(
            model_name="release",
            old_name="started_at",
            new_name="release_date",
        ),
        migrations.AddField(
            model_name="release",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when this record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="release",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this record was last updated"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Timestamp when this record was created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="track",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this record was last updated"
            ),
        ),
    ]
