# Generated by Django 5.2.6 on 2025-09-11 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0005_rename_started_at_release_release_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="track",
            old_name="notes",
            new_name="remarks",
        ),
    ]
