# Generated by Django 5.2.9 on 2026-01-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0007_alter_track_workout"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="order",
            field=models.IntegerField(
                blank=True,
                help_text="Optional field to specify custom ordering",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="order",
            field=models.IntegerField(
                blank=True,
                help_text="Optional field to specify custom ordering",
                null=True,
            ),
        ),
    ]
