# Generated by Django 5.2.9 on 2026-01-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0008_release_order_track_order"),
    ]

    def populate_release_order(apps, schema_editor):
        Release = apps.get_model("tracks", "Release")
        for index, release in enumerate(Release.objects.order_by("number", "branding")):
            release.order = index + 1
            release.save(update_fields=["order"])

    def clear_release_order(apps, schema_editor):
        Release = apps.get_model("tracks", "Release")
        for release in Release.objects.all():
            release.order = None
            release.save(update_fields=["order"])

    def populate_track_order(apps, schema_editor):
        Track = apps.get_model("tracks", "Track")
        tracks = Track.objects.all().order_by("release__order", "number")
        for index, track in enumerate(tracks):
            track.order = index + 1
            track.save(update_fields=["order"])

    def clear_track_order(apps, schema_editor):
        Track = apps.get_model("tracks", "Track")
        for track in Track.objects.all():
            track.order = None
            track.save(update_fields=["order"])

    operations = [
        migrations.RunPython(populate_release_order, clear_release_order),
        migrations.RunPython(populate_track_order, clear_track_order),
    ]
